### ISSUE TITLE
Prediction Result Not Displaying Correctly.

### ISSUE THREAD

**Issue by Rohit1726** [vaishnavid0604/agriculture-portal#3]
@vaishnavid0604  I am working on a crop and rainfall prediction system to forecast rainfall for different regions and months. The system correctly identifies the region as "NORTH INTERIOR KARNATAKA" and the month as "SEP." However, when attempting to display the predicted rainfall value in millimeters, only the header information is shown, and the actual prediction result is missing.

Steps to Reproduce:

Provide input for the region: "NORTH INTERIOR KARNATAKA"
Provide input for the month: "SEP"
Initiate the prediction process.
Observe the output displayed, which only includes the region and month, but not the predicted rainfall value.
Expected Outcome:
The system should display the predicted rainfall value in millimeters for the specified region ("NORTH INTERIOR KARNATAKA") and month ("SEP").

Additional Information:

I have verified that the predicted rainfall data is being correctly fetched from the data source or model.
There are no apparent issues with variable names or data formatting in the code responsible for displaying the result.
I have tried incorporating print statements and debugging tools to trace the issue, but have not been able to identify the root cause.

**Comment by vaishnavid0604** [comment]
Run rainfall_prediction.py alone in shell to check for errors, if it gives desired results on shell, then it should work here also.
